"""
HTML Report Generator
Generate comprehensive HTML reports for EDA and model results
"""

import pandas as pd
import numpy as np
from typing import Dict, Any, List, Optional
import json
from datetime import datetime
import base64
import io
import logging

logger = logging.getLogger(__name__)

class ReportGenerator:
    """Generate HTML reports for EDA and model results"""
    
    def __init__(self):
        self.template_style = """
        <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
            .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #3498db; padding-bottom: 20px; }
            .section { margin: 30px 0; }
            .section h2 { color: #2c3e50; border-left: 4px solid #3498db; padding-left: 15px; }
            .section h3 { color: #34495e; margin-top: 25px; }
            .metric-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }
            .metric-card { background: #ecf0f1; padding: 20px; border-radius: 8px; text-align: center; }
            .metric-value { font-size: 2em; font-weight: bold; color: #2980b9; }
            .metric-label { color: #7f8c8d; margin-top: 5px; }
            .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            .table th, .table td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
            .table th { background-color: #3498db; color: white; }
            .table tr:hover { background-color: #f5f5f5; }
            .warning { background-color: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 5px; margin: 10px 0; }
            .error { background-color: #f8d7da; border: 1px solid #f5c6cb; padding: 15px; border-radius: 5px; margin: 10px 0; }
            .success { background-color: #d4edda; border: 1px solid #c3e6cb; padding: 15px; border-radius: 5px; margin: 10px 0; }
            .info { background-color: #d1ecf1; border: 1px solid #bee5eb; padding: 15px; border-radius: 5px; margin: 10px 0; }
            .plot-container { text-align: center; margin: 20px 0; }
            .recommendations { background: #e8f6f3; padding: 20px; border-radius: 8px; border-left: 4px solid #27ae60; }
            .timestamp { text-align: right; color: #7f8c8d; font-size: 0.9em; margin-top: 30px; }
        </style>
        """
    
    async def generate_eda_report(self, df: pd.DataFrame, eda_results: Dict[str, Any]) -> str:
        """Generate comprehensive EDA HTML report"""
        
        try:
            html_content = f"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>EDA Report - {eda_results.get('dataset_id', 'Dataset')}</title>
                {self.template_style}
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>📊 Exploratory Data Analysis Report</h1>
                        <p>Dataset: <strong>{eda_results.get('dataset_id', 'Unknown')}</strong></p>
                        <p>Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                    </div>
            """
            
            # Dataset Overview Section
            html_content += self._generate_overview_section(df, eda_results)
            
            # Data Quality Section
            html_content += self._generate_data_quality_section(eda_results)
            
            # Statistical Analysis Section
            html_content += self._generate_statistical_section(eda_results)
            
            # Relationships Section
            html_content += self._generate_relationships_section(eda_results)
            
            # Recommendations Section
            html_content += self._generate_recommendations_section(eda_results)
            
            html_content += f"""
                    <div class="timestamp">
                        Report generated by AI EDA Platform
                    </div>
                </div>
            </body>
            </html>
            """
            
            return html_content
            
        except Exception as e:
            logger.error(f"Failed to generate EDA report: {str(e)}")
            return self._generate_error_report("EDA Report Generation Failed", str(e))
    
    async def generate_model_report(self, model_results: Dict[str, Any]) -> str:
        """Generate comprehensive model training HTML report"""
        
        try:
            html_content = f"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Model Training Report</title>
                {self.template_style}
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>🤖 Model Training Report</h1>
                        <p>Task Type: <strong>{model_results.get('task_type', 'Unknown').title()}</strong></p>
                        <p>Target: <strong>{model_results.get('target_column', 'Unknown')}</strong></p>
                        <p>Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                    </div>
            """
            
            # Training Overview
            html_content += self._generate_training_overview_section(model_results)
            
            # Model Performance Comparison
            html_content += self._generate_model_comparison_section(model_results)
            
            # Best Model Details
            html_content += self._generate_best_model_section(model_results)
            
            # Recommendations
            html_content += self._generate_model_recommendations_section(model_results)
            
            html_content += f"""
                    <div class="timestamp">
                        Report generated by AI EDA Platform
                    </div>
                </div>
            </body>
            </html>
            """
            
            return html_content
            
        except Exception as e:
            logger.error(f"Failed to generate model report: {str(e)}")
            return self._generate_error_report("Model Report Generation Failed", str(e))
    
    def _generate_overview_section(self, df: pd.DataFrame, eda_results: Dict[str, Any]) -> str:
        """Generate dataset overview section"""
        
        analyses = eda_results.get('analyses', {})
        basic_stats = analyses.get('basic_statistics', {})
        overview = basic_stats.get('overview', {})
        
        html = """
        <div class="section">
            <h2>📋 Dataset Overview</h2>
            <div class="metric-grid">
        """
        
        metrics = [
            ("Total Rows", f"{overview.get('total_rows', 0):,}"),
            ("Total Columns", f"{overview.get('total_columns', 0)}"),
            ("Numeric Columns", f"{overview.get('numeric_columns', 0)}"),
            ("Categorical Columns", f"{overview.get('categorical_columns', 0)}"),
            ("Memory Usage", f"{overview.get('memory_usage_mb', 0):.1f} MB"),
            ("Duplicate Rows", f"{overview.get('duplicate_rows', 0):,}")
        ]
        
        for label, value in metrics:
            html += f"""
                <div class="metric-card">
                    <div class="metric-value">{value}</div>
                    <div class="metric-label">{label}</div>
                </div>
            """
        
        html += "</div>"
        
        # Column Information Table
        column_info = basic_stats.get('column_info', [])
        if column_info:
            html += """
            <h3>Column Details</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Column</th>
                        <th>Data Type</th>
                        <th>Non-Null Count</th>
                        <th>Missing %</th>
                        <th>Unique Values</th>
                    </tr>
                </thead>
                <tbody>
            """
            
            for col in column_info[:20]:  # Show first 20 columns
                html += f"""
                    <tr>
                        <td><strong>{col.get('column', '')}</strong></td>
                        <td>{col.get('dtype', '')}</td>
                        <td>{col.get('non_null_count', 0):,}</td>
                        <td>{col.get('null_percentage', 0):.1f}%</td>
                        <td>{col.get('unique_count', 0):,}</td>
                    </tr>
                """
            
            html += "</tbody></table>"
        
        html += "</div>"
        return html
    
    def _generate_data_quality_section(self, eda_results: Dict[str, Any]) -> str:
        """Generate data quality section"""
        
        analyses = eda_results.get('analyses', {})
        missing_analysis = analyses.get('missing_values', {})
        
        html = """
        <div class="section">
            <h2>🔍 Data Quality Assessment</h2>
        """
        
        # Missing Values Summary
        overall_missing = missing_analysis.get('overall_missing_percentage', 0)
        if overall_missing > 0:
            status_class = "error" if overall_missing > 20 else "warning" if overall_missing > 5 else "info"
            html += f"""
            <div class="{status_class}">
                <strong>Missing Values:</strong> {overall_missing:.1f}% of total data points are missing
            </div>
            """
            
            columns_with_missing = missing_analysis.get('columns_with_missing', {})
            if columns_with_missing:
                html += """
                <h3>Columns with Missing Values</h3>
                <table class="table">
                    <thead>
                        <tr><th>Column</th><th>Missing Count</th><th>Missing %</th></tr>
                    </thead>
                    <tbody>
                """
                
                missing_percentages = missing_analysis.get('missing_percentages', {})
                for col, count in list(columns_with_missing.items())[:10]:
                    percentage = missing_percentages.get(col, 0)
                    html += f"""
                        <tr>
                            <td>{col}</td>
                            <td>{count:,}</td>
                            <td>{percentage:.1f}%</td>
                        </tr>
                    """
                
                html += "</tbody></table>"
        else:
            html += '<div class="success"><strong>✅ No missing values detected!</strong></div>'
        
        # Recommendations
        recommendations = missing_analysis.get('recommendations', [])
        if recommendations:
            html += '<div class="recommendations"><h3>💡 Data Quality Recommendations</h3><ul>'
            for rec in recommendations:
                suggestion = rec.get('suggestion', '')
                html += f'<li>{suggestion}</li>'
            html += '</ul></div>'
        
        html += "</div>"
        return html
    
    def _generate_statistical_section(self, eda_results: Dict[str, Any]) -> str:
        """Generate statistical analysis section"""
        
        analyses = eda_results.get('analyses', {})
        
        html = """
        <div class="section">
            <h2>📈 Statistical Analysis</h2>
        """
        
        # Distribution Analysis
        dist_analysis = analyses.get('distributions', {})
        if dist_analysis:
            html += "<h3>Distribution Characteristics</h3>"
            
            dist_data = dist_analysis.get('distribution_analysis', {})
            skewed_cols = []
            
            for col, analysis in dist_data.items():
                shape = analysis.get('distribution_shape', {})
                skewness = shape.get('skewness', 0)
                if abs(skewness) > 1:
                    skewed_cols.append((col, skewness))
            
            if skewed_cols:
                html += """
                <div class="warning">
                    <strong>Skewed Distributions Detected:</strong>
                    <ul>
                """
                for col, skew in skewed_cols[:5]:
                    direction = "right" if skew > 0 else "left"
                    html += f'<li><strong>{col}</strong>: {direction}-skewed (skewness: {skew:.2f})</li>'
                html += "</ul></div>"
        
        # Outlier Analysis
        outlier_analysis = analyses.get('outliers', {})
        if outlier_analysis:
            html += "<h3>Outlier Detection</h3>"
            
            outlier_summary = outlier_analysis.get('outlier_summary', {})
            high_outlier_cols = [(col, info) for col, info in outlier_summary.items() 
                               if info.get('severity') == 'high']
            
            if high_outlier_cols:
                html += """
                <div class="warning">
                    <strong>High Outlier Concentration:</strong>
                    <table class="table">
                        <thead>
                            <tr><th>Column</th><th>Outlier Count</th><th>Outlier %</th></tr>
                        </thead>
                        <tbody>
                """
                for col, info in high_outlier_cols[:5]:
                    html += f"""
                        <tr>
                            <td>{col}</td>
                            <td>{info.get('total_outliers', 0):,}</td>
                            <td>{info.get('outlier_percentage', 0):.1f}%</td>
                        </tr>
                    """
                html += "</tbody></table></div>"
        
        html += "</div>"
        return html
    
    def _generate_relationships_section(self, eda_results: Dict[str, Any]) -> str:
        """Generate relationships analysis section"""
        
        analyses = eda_results.get('analyses', {})
        corr_analysis = analyses.get('correlations', {})
        
        html = """
        <div class="section">
            <h2>🔗 Feature Relationships</h2>
        """
        
        if corr_analysis:
            strong_corrs = corr_analysis.get('strong_correlations', {}).get('pearson', [])
            
            if strong_corrs:
                html += """
                <h3>Strong Correlations (|r| ≥ 0.7)</h3>
                <table class="table">
                    <thead>
                        <tr><th>Feature 1</th><th>Feature 2</th><th>Correlation</th><th>Strength</th></tr>
                    </thead>
                    <tbody>
                """
                
                for corr in strong_corrs[:10]:
                    strength = corr.get('strength', 'moderate')
                    correlation = corr.get('correlation', 0)
                    color = '#e74c3c' if abs(correlation) > 0.9 else '#f39c12' if abs(correlation) > 0.8 else '#27ae60'
                    
                    html += f"""
                        <tr>
                            <td>{corr.get('feature_1', '')}</td>
                            <td>{corr.get('feature_2', '')}</td>
                            <td style="color: {color}; font-weight: bold;">{correlation:.3f}</td>
                            <td>{strength.replace('_', ' ').title()}</td>
                        </tr>
                    """
                
                html += "</tbody></table>"
                
                if len([c for c in strong_corrs if abs(c.get('correlation', 0)) > 0.9]) > 0:
                    html += """
                    <div class="warning">
                        <strong>⚠️ Multicollinearity Warning:</strong> Very high correlations detected. 
                        Consider feature selection or dimensionality reduction techniques.
                    </div>
                    """
            else:
                html += '<div class="info">No strong correlations found between features.</div>'
        
        html += "</div>"
        return html
    
    def _generate_recommendations_section(self, eda_results: Dict[str, Any]) -> str:
        """Generate recommendations section"""
        
        html = """
        <div class="section">
            <h2>💡 Recommendations</h2>
            <div class="recommendations">
        """
        
        # Collect recommendations from all analyses
        all_recommendations = []
        
        analyses = eda_results.get('analyses', {})
        for analysis_type, analysis_data in analyses.items():
            if isinstance(analysis_data, dict):
                recommendations = analysis_data.get('recommendations', [])
                for rec in recommendations:
                    if isinstance(rec, dict):
                        all_recommendations.append(rec.get('suggestion', str(rec)))
                    else:
                        all_recommendations.append(str(rec))
        
        if all_recommendations:
            html += "<h3>Key Recommendations for Data Preprocessing:</h3><ul>"
            for rec in all_recommendations[:10]:  # Top 10 recommendations
                html += f"<li>{rec}</li>"
            html += "</ul>"
        else:
            html += "<p>No specific recommendations generated. Dataset appears to be in good condition for analysis.</p>"
        
        # General ML recommendations
        html += """
        <h3>General Machine Learning Recommendations:</h3>
        <ul>
            <li>Consider feature scaling for algorithms sensitive to feature magnitude</li>
            <li>Evaluate feature importance after model training</li>
            <li>Use cross-validation for robust model evaluation</li>
            <li>Monitor for data drift in production</li>
            <li>Implement proper train/validation/test splits</li>
        </ul>
        """
        
        html += "</div></div>"
        return html
    
    def _generate_training_overview_section(self, model_results: Dict[str, Any]) -> str:
        """Generate training overview section"""
        
        dataset_info = model_results.get('dataset_info', {})
        
        html = """
        <div class="section">
            <h2>🎯 Training Overview</h2>
            <div class="metric-grid">
        """
        
        metrics = [
            ("Total Samples", f"{dataset_info.get('total_samples', 0):,}"),
            ("Training Samples", f"{dataset_info.get('train_samples', 0):,}"),
            ("Test Samples", f"{dataset_info.get('test_samples', 0):,}"),
            ("Features", f"{dataset_info.get('n_features', 0)}"),
            ("Task Type", model_results.get('task_type', 'Unknown').title()),
            ("Target Column", model_results.get('target_column', 'Unknown'))
        ]
        
        for label, value in metrics:
            html += f"""
                <div class="metric-card">
                    <div class="metric-value">{value}</div>
                    <div class="metric-label">{label}</div>
                </div>
            """
        
        html += "</div></div>"
        return html
    
    def _generate_model_comparison_section(self, model_results: Dict[str, Any]) -> str:
        """Generate model comparison section"""
        
        models = model_results.get('models', {})
        task_type = model_results.get('task_type', 'classification')
        
        html = """
        <div class="section">
            <h2>⚖️ Model Performance Comparison</h2>
        """
        
        if models:
            html += """
            <table class="table">
                <thead>
                    <tr>
                        <th>Model</th>
                        <th>Status</th>
            """
            
            # Add metric columns based on task type
            if task_type == 'classification':
                html += "<th>Accuracy</th><th>F1-Score</th><th>Precision</th><th>Recall</th>"
            else:
                html += "<th>RMSE</th><th>MAE</th><th>R²</th>"
            
            html += "</tr></thead><tbody>"
            
            for model_name, model_data in models.items():
                status = model_data.get('status', 'unknown')
                status_color = '#27ae60' if status == 'completed' else '#e74c3c'
                
                html += f"""
                    <tr>
                        <td><strong>{model_name}</strong></td>
                        <td style="color: {status_color};">{status.title()}</td>
                """
                
                if status == 'completed':
                    metrics = model_data.get('metrics', {}).get('test', {})
                    
                    if task_type == 'classification':
                        html += f"""
                            <td>{metrics.get('accuracy', 0):.4f}</td>
                            <td>{metrics.get('f1_score', 0):.4f}</td>
                            <td>{metrics.get('precision', 0):.4f}</td>
                            <td>{metrics.get('recall', 0):.4f}</td>
                        """
                    else:
                        html += f"""
                            <td>{metrics.get('rmse', 0):.4f}</td>
                            <td>{metrics.get('mae', 0):.4f}</td>
                            <td>{metrics.get('r2', 0):.4f}</td>
                        """
                else:
                    # Fill with N/A for failed models
                    n_metrics = 4 if task_type == 'classification' else 3
                    html += "<td>N/A</td>" * n_metrics
                
                html += "</tr>"
            
            html += "</tbody></table>"
        
        html += "</div>"
        return html
    
    def _generate_best_model_section(self, model_results: Dict[str, Any]) -> str:
        """Generate best model details section"""
        
        best_model_name = model_results.get('best_model')
        
        html = """
        <div class="section">
            <h2>🏆 Best Model</h2>
        """
        
        if best_model_name:
            models = model_results.get('models', {})
            best_model_data = models.get(best_model_name, {})
            
            html += f"""
            <div class="success">
                <h3>{best_model_name}</h3>
                <p><strong>Status:</strong> {best_model_data.get('status', 'Unknown').title()}</p>
            """
            
            if best_model_data.get('status') == 'completed':
                metrics = best_model_data.get('metrics', {})
                test_metrics = metrics.get('test', {})
                train_metrics = metrics.get('train', {})
                
                html += "<h4>Performance Metrics:</h4><ul>"
                
                task_type = model_results.get('task_type', 'classification')
                if task_type == 'classification':
                    html += f"""
                        <li><strong>Test Accuracy:</strong> {test_metrics.get('accuracy', 0):.4f}</li>
                        <li><strong>Test F1-Score:</strong> {test_metrics.get('f1_score', 0):.4f}</li>
                        <li><strong>Training Accuracy:</strong> {train_metrics.get('accuracy', 0):.4f}</li>
                    """
                else:
                    html += f"""
                        <li><strong>Test RMSE:</strong> {test_metrics.get('rmse', 0):.4f}</li>
                        <li><strong>Test R²:</strong> {test_metrics.get('r2', 0):.4f}</li>
                        <li><strong>Training RMSE:</strong> {train_metrics.get('rmse', 0):.4f}</li>
                    """
                
                html += "</ul>"
                
                # Check for overfitting
                if task_type == 'classification':
                    train_acc = train_metrics.get('accuracy', 0)
                    test_acc = test_metrics.get('accuracy', 0)
                    if train_acc - test_acc > 0.1:
                        html += '<div class="warning">⚠️ Potential overfitting detected (training accuracy significantly higher than test accuracy)</div>'
                
            html += "</div>"
        else:
            html += '<div class="error">No best model identified. Check training results.</div>'
        
        html += "</div>"
        return html
    
    def _generate_model_recommendations_section(self, model_results: Dict[str, Any]) -> str:
        """Generate model recommendations section"""
        
        html = """
        <div class="section">
            <h2>📋 Deployment Recommendations</h2>
            <div class="recommendations">
        """
        
        best_model = model_results.get('best_model')
        task_type = model_results.get('task_type', 'classification')
        
        if best_model:
            html += f"""
            <h3>Recommended Model: {best_model}</h3>
            <ul>
                <li>Deploy the <strong>{best_model}</strong> model for production use</li>
                <li>Implement proper input validation and preprocessing pipeline</li>
                <li>Set up monitoring for model performance degradation</li>
                <li>Consider A/B testing before full deployment</li>
            </ul>
            """
        
        html += """
        <h3>General Recommendations:</h3>
        <ul>
            <li>Regularly retrain models with new data to maintain performance</li>
            <li>Monitor for data drift and concept drift</li>
            <li>Implement proper logging and error handling</li>
            <li>Set up alerts for unusual prediction patterns</li>
            <li>Document model assumptions and limitations</li>
        </ul>
        """
        
        if task_type == 'classification':
            html += """
            <h3>Classification-Specific Recommendations:</h3>
            <ul>
                <li>Monitor precision and recall for each class</li>
                <li>Consider class imbalance in production data</li>
                <li>Implement confidence thresholds for predictions</li>
            </ul>
            """
        else:
            html += """
            <h3>Regression-Specific Recommendations:</h3>
            <ul>
                <li>Monitor prediction intervals and uncertainty</li>
                <li>Track residual patterns over time</li>
                <li>Consider ensemble methods for improved robustness</li>
            </ul>
            """
        
        html += "</div></div>"
        return html
    
    def _generate_error_report(self, title: str, error_message: str) -> str:
        """Generate error report HTML"""
        
        return f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Error Report</title>
            {self.template_style}
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>❌ {title}</h1>
                </div>
                <div class="error">
                    <h3>Error Details:</h3>
                    <p>{error_message}</p>
                </div>
                <div class="timestamp">
                    Error occurred on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
                </div>
            </div>
        </body>
        </html>
        """
